services:
  # Service unifié optimisé pour Saloneo
  - type: web
    name: saloneo-deploy
    env: node
    plan: starter
    region: oregon
    buildCommand: |
      echo "🚀 === BUILD SALONEO ===" &&
      echo "📍 Répertoire: $(pwd)" &&
      echo "📂 Contenu:" &&
      ls -la &&
      echo "" &&
      echo "🎯 === BUILD FRONTEND ===" &&
      cd beauty-flow &&
      echo "📦 Installation dépendances frontend..." &&
      npm ci --only=production &&
      echo "🏗️ Build Vite..." &&
      npm run build &&
      echo "✅ Vérification build frontend:" &&
      ls -la dist/ &&
      echo "" &&
      echo "🎯 === COPIE DU FRONTEND ===" &&
      cd .. &&
      echo "📁 Copie du frontend buildé..." &&
      cp -r beauty-flow/dist ./dist &&
      echo "📁 Copie des uploads..." &&
      mkdir -p uploads &&
      echo "" &&
      echo "✅ === VÉRIFICATION FINALE ===" &&
      echo "📁 Structure finale:" &&
      ls -la &&
      echo "📁 Contenu dist:" &&
      ls -la dist/ &&
      echo "📄 Index.html:" &&
      ls -la dist/index.html &&
      echo "🎉 === BUILD TERMINÉ AVEC SUCCÈS ==="
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://saloneo-user:s8OfObmiaiug2zOt@clustertriogeneral.hvkpnvh.mongodb.net/saloneo?retryWrites=true&w=majority&appName=ClusterTrioGeneral
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d
      - key: FRONTEND_URL
        value: https://saloneo-app.onrender.com
      - key: CORS_ORIGIN
        value: https://saloneo-app.onrender.com
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: UPLOAD_DIR
        value: uploads
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: LOG_LEVEL
        value: info
