services:
  # Service unifié (frontend + backend)
  - type: web
    name: saloneo-app
    env: node
    plan: starter
    region: oregon
    buildCommand: |
      echo "🚀 === DÉBUT BUILD SALONEO ROBUSTE V3 ===" &&
      echo "📍 Répertoire de travail: $(pwd)" &&
      echo "📂 Contenu du répertoire:" &&
      ls -la &&
      echo "🔧 === INSTALLATION GLOBALE DES OUTILS ===" &&
      npm install -g typescript vite @types/node &&
      echo "🏗️ === BUILD BACKEND TYPESCRIPT ===" &&
      cd beauty-flow-backend &&
      echo "📦 Installation des dépendances backend..." &&
      npm install &&
      echo "🔨 Compilation TypeScript..." &&
      npx tsc &&
      echo "✅ Vérification backend compilé..." &&
      if [ -f "dist/app.js" ]; then 
        echo "✅ Backend compilé avec succès:" && ls -la dist/
      else 
        echo "❌ Erreur compilation backend" && exit 1
      fi &&
      echo "🎨 === BUILD FRONTEND REACT ===" &&
      cd ../beauty-flow &&
      echo "📦 Installation des dépendances frontend..." &&
      npm install &&
      echo "🎯 Build frontend avec variables d'environnement..." &&
      VITE_API_URL=https://saloneo-app.onrender.com/api VITE_ENV=production VITE_APP_NAME=Saloneo VITE_SITE_URL=https://saloneo-app.onrender.com npm run build &&
      echo "✅ Vérification frontend build..." &&
      if [ -d "dist" ] && [ -f "dist/index.html" ]; then 
        echo "✅ Frontend build réussi:" && ls -la dist/ && echo "📄 Index.html:" && head -3 dist/index.html
      else 
        echo "❌ Erreur build frontend" && exit 1
      fi &&
      echo "🔧 === INSTALLATION DÉPENDANCES RACINE ===" &&
      cd .. &&
      npm install &&
      echo "🎉 === BUILD TERMINÉ AVEC SUCCÈS ==="
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://saloneo-user:s8OfObmiaiug2zOt@clustertriogeneral.hvkpnvh.mongodb.net/saloneo?retryWrites=true&w=majority&appName=ClusterTrioGeneral
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d
      - key: FRONTEND_URL
        value: https://saloneo-app.onrender.com
      - key: CORS_ORIGIN
        value: https://saloneo-app.onrender.com
      - key: VITE_API_URL
        value: https://saloneo-app.onrender.com/api
      - key: VITE_ENV
        value: production
      - key: VITE_APP_NAME
        value: Saloneo
      - key: VITE_SITE_URL
        value: https://saloneo-app.onrender.com
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: UPLOAD_DIR
        value: uploads
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: LOG_LEVEL
        value: info
